name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "👋  Hello and thanks for your first issue here! We appreciate your contribution and your feedback.We will get back to you soon"
        pr-message: "🎉 Wow, your first pull request! Thank you for contributing! We'll review this shortly."
